### ISSUE TITLE
bug fix HTTP mixed-content warning by editing HTML

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/html5-kitchen-sink-test#2]
This site is live on [mirai.audio](https://mirai.audio/html5-kitchen-sink-test/#embedded__images) but is throwing a HTTP mixed-content warning because the `<img>` tags on the page refer to non-HTTPS URLs.

These errors appear in the console as:

```
Loading mixed (insecure) display content “http://placekitten.com/420/420” on a secure page
```

They appear in the browser as follow:

![Screen Shot 2019-09-30 at 10 02 20 AM](https://user-images.githubusercontent.com/51207/65886744-e2a4cb00-e36a-11e9-8118-03354df2db66.png)

* [ ] replace hard coded links to `http://` with `https://`
* [ ] verify mixed-content warnings are gone

**Comment by rajkharvar** [comment]
@0xadada I would like to work on this.

**Comment by 0xadada** [comment]
@rajkharvar yes, please do go ahead! 👍

**Comment by 0xadada** [comment]
fixed by https://github.com/mirai-audio/html5-kitchen-sink-test/pull/3/commits/ae99697dbd55fd0048691203568a667b94fbfe4c
